### ISSUE TITLE
Using yml style VSTS build $Env:SYSTEM_ACCESSTOKEN is blank

### ISSUE THREAD

**Issue by chudson121** [fakhrulhilal/TFSGitDownloader#1]
-Update: looks like the vsts build system is not injecting that variable to be used in the yaml except while using powershell, it is not available in command line tasks either

I was finally able to get yaml working but it is using powershell
- powershell: |
     $BUILDREPO = "MYREPONAME"
     $BUILDSCRIPTSPATH = "{0}\buildscripts" -f $env:SYSTEM_DEFAULTWORKINGDIRECTORY
     $CLONEURI = "{0}{1}/_git/{2}" -f $env:SYSTEM_TEAMFOUNDATIONSERVERURI,$env:SYSTEM_TEAMPROJECT,$BUILDREPO
     $GITCMD = 'git clone **-c http.extraheader="AUTHORIZATION`: bearer ${env:TOKEN}**" --single-branch --progress -b master "${CLONEURI}" "${BUILDSCRIPTSPATH}" '
   
     Invoke-Expression $GITCMD
    env:
      **TOKEN: $(system.accesstoken)**
    displayName: Get Build Scripts

Hi I am using your plugin and with a normal build it works great, but when i am leveraging it in the .vsts-ci.yml style build the output shows the extraheader="Authorization: bearer "  << it is blank for the token. I am able to access that token in a powershell (example below). 

**.vsts-ci.yml steps**
  steps: 
  - powershell: |
      $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/build/definitions/$($env:SYSTEM_DEFINITIONID)?api-version=2.0"
      Write-Host "URL: $url"
      $definition = Invoke-RestMethod -Uri $url -Headers @{ Authorization = "Bearer $env:TOKEN" }
      Write-Host "Definition = $($definition | ConvertTo-Json)"
    env:
      TOKEN: $(system.accesstoken)

  - task: fakhrulhilal-maktum.GitDownloader.git-downloader.GitDownloader@0
    displayName: Build Scripts
    inputs:
      RepositoryUrl: '$(Build.Repository.GitUri)/BuildAndReleaseUtilities'

**Log output from the plugin**
2018-05-23T18:00:21.0929603Z ##[debug]Evaluating condition for step: 'Build Scripts'
2018-05-23T18:00:21.0931591Z ##[debug]Evaluating: succeeded()
2018-05-23T18:00:21.0932058Z ##[debug]Evaluating succeeded:
2018-05-23T18:00:21.0932663Z ##[debug]=> True
2018-05-23T18:00:21.0933208Z ##[debug]Result: True
2018-05-23T18:00:21.0933754Z ##[section]Starting: Build Scripts
2018-05-23T18:00:21.1155270Z ==============================================================================
2018-05-23T18:00:21.1155616Z Task         : Git Repository Downloader
2018-05-23T18:00:21.1155921Z Description  : Download additional git repository from public repository or this TFS
2018-05-23T18:00:21.1156200Z Version      : 0.2.15
2018-05-23T18:00:21.1156424Z Author       : Fakhrulhilal Maktum
2018-05-23T18:00:21.1156736Z Help         : [More information](https://github.com/fakhrulhilal/TFSGitDownloader/blob/master/README.md)
2018-05-23T18:00:21.1158558Z ==============================================================================
2018-05-23T18:00:21.1422158Z Preparing task execution handler.
2018-05-23T18:00:24.0339599Z Executing the powershell script: D:\a\_tasks\GitDownloader_56033f91-aeb8-4316-b19a-bcb721f4705b\0.2.15\GitDownloader.ps1
2018-05-23T18:00:24.0371513Z ##[debug]PowerShellHandler.Execute - AddCommand(D:\a\_tasks\GitDownloader_56033f91-aeb8-4316-b19a-bcb721f4705b\0.2.15\GitDownloader.ps1)
2018-05-23T18:00:24.0372238Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2018-05-23T18:00:24.0372908Z ##[debug]PowerShellHandler.Execute - AddParameter(RepositoryUrl=$(Build.Repository.GitUri)/BuildAndReleaseUtilities)
2018-05-23T18:00:24.0373617Z ##[debug]PowerShellHandler.Execute - AddParameter(RepositoryPath=)
2018-05-23T18:00:24.0374036Z ##[debug]PowerShellHandler.Execute - AddParameter(BranchTag=master)
2018-05-23T18:00:24.0374668Z ##[debug]PowerShellHandler.Execute - AddParameter(Clean=false)
2018-05-23T18:00:24.2020998Z ##[debug]PowerShellHandler.Execute - Invoke
2018-05-23T18:00:24.8625261Z ##[debug]Processed: ##vso[task.setvariable variable=Build.Repository.GitUri]https://Defaultvsts.visualstudio.com/Default/_git
2018-05-23T18:00:24.8625725Z 
2018-05-23T18:00:24.8625867Z 
2018-05-23T18:00:24.9364940Z ##[debug]Processed: ##vso[task.setvariable variable=Build.GitDirectory]D:\a\1\git
2018-05-23T18:00:24.9365442Z 
2018-05-23T18:00:24.9366473Z 
2018-05-23T18:00:24.9538628Z Creating git directory: D:\a\1\git
2018-05-23T18:00:24.9539199Z 
2018-05-23T18:00:24.9539428Z 
2018-05-23T18:00:25.0227508Z Cloning https://Defaultvsts.visualstudio.com/Default/_git/BuildAndReleaseUtilities for branch/tag 'master' into D:\a\1\git\BuildAndReleaseUtilities
2018-05-23T18:00:25.0227853Z 
2018-05-23T18:00:25.0227996Z 
2018-05-23T18:00:25.4110725Z  git -c http.extraheader="Authorization: bearer " clone --single-branch --progress -b master "https://Defaultvsts.visualstudio.com/Default/_git/BuildAndReleaseUtilities" "D:\a\1\git\BuildAndReleaseUtilities" 
2018-05-23T18:00:25.4111406Z 
2018-05-23T18:00:25.4112471Z 
2018-05-23T18:00:25.7210468Z Cloning into 'D:\a\1\git\BuildAndReleaseUtilities'...
2018-05-23T18:00:27.7082244Z /usr/bin/bash: /dev/tty: No such device or address
2018-05-23T18:00:27.7083260Z 
2018-05-23T18:00:27.7122699Z error: failed to execute prompt script (exit code 1)
2018-05-23T18:00:27.7123328Z fatal: could not read Username for 'https://Defaultvsts.visualstudio.com': No error
2018-05-23T18:00:27.7123596Z 
2018-05-23T18:00:28.4677860Z ##[error]System.Management.Automation.RuntimeException: Execution failed with exit code 128 ---> System.Management.Automation.RuntimeException: Execution failed with exit code 128
2018-05-23T18:00:28.4693507Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.RuntimeException: Execution failed with exit code 128 ---> System.Management.Automation.RuntimeException: Execution failed with exit code 128
2018-05-23T18:00:28.4694375Z    --- End of inner exception stack trace ---
2018-05-23T18:00:28.4694771Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2018-05-23T18:00:28.4699714Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2018-05-23T18:00:28.4700176Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2018-05-23T18:00:28.4700672Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-05-23T18:00:28.4701184Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2018-05-23T18:00:28.4701667Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2018-05-23T18:00:28.4850167Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2018-05-23T18:00:28.4866942Z ##[section]Finishing: Build Scripts

**Comment by fakhrulhilal** [comment]
@chudson121 by referring the [document](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-token.md), it looks like the token environment variable is not exposed by default. So we need to expose by own self with the same name as [predefined variable](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts#systemaccesstoken). So the build config should be as follows:
```yml
- task: fakhrulhilal-maktum.GitDownloader.git-downloader.GitDownloader@0
  displayName: Get build tools
  inputs:
    RepositoryUrl: '$(System.TeamFoundationCollectionUri)/OpenSource/_git/BuildTools'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

**Comment by fakhrulhilal** [comment]
@chudson121 can you confirm that it works now? I'm closing this tomorrow if no respond given.
