### ISSUE TITLE
System.Management.Automation.RuntimeException when cloning

### ISSUE THREAD

**Issue by Scott-Emberson** [fakhrulhilal/TFSGitDownloader#7]
When trying to fetch the git repo, I get the following error. 

`2019-07-19T10:55:19.9974284Z ##[debug]Evaluating condition for step: 'Fetch git: $(Build.Repository.GitUri)/Automation.API.Sanity'
2019-07-19T10:55:19.9975377Z ##[debug]Evaluating: succeeded()
2019-07-19T10:55:19.9975724Z ##[debug]Evaluating succeeded:
2019-07-19T10:55:19.9976195Z ##[debug]=> True
2019-07-19T10:55:19.9976748Z ##[debug]Result: True
2019-07-19T10:55:19.9977668Z ##[section]Starting: Fetch git: $(Build.Repository.GitUri)/Automation.API.Sanity
2019-07-19T10:55:19.9981219Z ==============================================================================
2019-07-19T10:55:19.9981502Z Task         : Git Repository Downloader
2019-07-19T10:55:19.9981666Z Description  : Download additional git repository from public repository or this TFS
2019-07-19T10:55:19.9981809Z Version      : 0.3.3
2019-07-19T10:55:19.9981965Z Author       : Fakhrulhilal Maktum
2019-07-19T10:55:19.9982063Z Help         : [More information](https://github.com/fakhrulhilal/TFSGitDownloader/blob/master/README.md)
2019-07-19T10:55:19.9982189Z ==============================================================================
2019-07-19T10:55:20.0124693Z Preparing task execution handler.
2019-07-19T10:55:20.1329391Z ##[debug]Restore default LegacyVSTSPowerShellHost.exe.config.
2019-07-19T10:55:20.1393450Z ##[debug]Add Proxy setting in LegacyVSTSPowerShellHost.exe.config file.
2019-07-19T10:55:20.8468281Z Executing the powershell script: R:\AzureAgents\05\_work\_tasks\GitDownloader_56033f91-aeb8-4316-b19a-bcb721f4705b\0.3.3\Save-GitRepository.ps1
2019-07-19T10:55:20.8469311Z ##[debug]PowerShellHandler.Execute - AddCommand(R:\AzureAgents\05\_work\_tasks\GitDownloader_56033f91-aeb8-4316-b19a-bcb721f4705b\0.3.3\Save-GitRepository.ps1)
2019-07-19T10:55:20.8469604Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2019-07-19T10:55:20.8469814Z ##[debug]PowerShellHandler.Execute - AddParameter(RepositoryUrl=$(Build.Repository.GitUri)/Automation.API.Sanity)
2019-07-19T10:55:20.8470008Z ##[debug]PowerShellHandler.Execute - AddParameter(RepositoryPath=)
2019-07-19T10:55:20.8470209Z ##[debug]PowerShellHandler.Execute - AddParameter(BranchTag=master)
2019-07-19T10:55:20.8470394Z ##[debug]PowerShellHandler.Execute - AddParameter(Clean=false)
2019-07-19T10:55:20.9468104Z ##[debug]PowerShellHandler.Execute - Invoke
2019-07-19T10:55:21.0225163Z ##[debug]Processed: ##vso[task.setvariable variable=Build.Repository.GitUri]https://TFSURL/TN/_git
2019-07-19T10:55:21.0225949Z 
2019-07-19T10:55:21.0226217Z 
2019-07-19T10:55:21.0463540Z ##[debug]Processed: ##vso[task.setvariable variable=Build.GitDirectory]R:\AzureAgents\05\_work\1\git
2019-07-19T10:55:21.0464350Z 
2019-07-19T10:55:21.0464960Z 
2019-07-19T10:55:21.0807032Z Cloning https://TFSURL/TN/_git/Automation.API.Sanity for branch/tag 'master' into R:\AzureAgents\05\_work\1\git\Automation.API.Sanity
2019-07-19T10:55:21.0808314Z 
2019-07-19T10:55:21.0809010Z 
2019-07-19T10:55:21.1229533Z git -c http.extraheader="Authorization: bearer ***" clone --single-branch --progress -b master "https://TFSURL/TN/_git/Automation.API.Sanity" "R:\AzureAgents\05\_work\1\git\Automation.API.Sanity"
2019-07-19T10:55:21.1230382Z 
2019-07-19T10:55:21.1231022Z 
2019-07-19T11:01:39.6939222Z ##[error]System.Management.Automation.RuntimeException: Execution failed with exit code -1073741502 ---> System.Management.Automation.RuntimeException: Execution failed with exit code -1073741502
2019-07-19T11:01:39.7326663Z ##[debug]Processed: ##vso[task.logissue type=error;]System.Management.Automation.RuntimeException: Execution failed with exit code -1073741502 ---> System.Management.Automation.RuntimeException: Execution failed with exit code -1073741502
2019-07-19T11:01:39.7327368Z    --- End of inner exception stack trace ---
2019-07-19T11:01:39.7327594Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2019-07-19T11:01:39.7327756Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2019-07-19T11:01:39.7443132Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2019-07-19T11:01:39.7443332Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-07-19T11:01:39.7443546Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2019-07-19T11:01:39.7443700Z    at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
2019-07-19T11:01:39.7752923Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -1.
2019-07-19T11:01:39.7957165Z ##[section]Finishing: Fetch git: $(Build.Repository.GitUri)/Automation.API.Sanity
`

**Comment by Scott-Emberson** [comment]
Looks like my system doesn't have enough resources.
